from torch import flatten
from .base_model import *
import torch.nn.functional as F


class Discriminator(BaseModel):
    """
    The discriminator predicts whether an image is real or fake, when the image is generated from the Generator.

    Input:
        - image: An image whose either real or generated by the Generator.
    Output:
        - A single value, representing the probability that the image is real.
    """

    def __init__(self, in_feature: int = 3, out_feature: int = 64):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Conv2d(in_channels=in_feature, out_channels=out_feature, kernel_size=4, stride=2, padding=1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(in_channels=out_feature, out_channels=2 * out_feature, kernel_size=4, stride=2, padding=1,
                      bias=False),
            nn.InstanceNorm2d(2 * out_feature),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(in_channels=2 * out_feature, out_channels=4 * out_feature, kernel_size=4, stride=2, padding=1,
                      bias=False),
            nn.InstanceNorm2d(4 * out_feature),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(in_channels=4 * out_feature, out_channels=8 * out_feature, kernel_size=4, stride=2, padding=1,
                      bias=False),
            nn.InstanceNorm2d(8 * out_feature),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(in_channels=8 * out_feature, out_channels=1, kernel_size=4, stride=1, padding=0, bias=False),
        )

    def forward(self, image):
        """
        Forward pass of the discriminator.
        """

        x = self.layers(image)
        x = F.avg_pool2d(x, x.size()[2:])
        return flatten(x, 1)
